export const backcities = [
  {
    iata: 'AXM',
    name: 'Aeropuerto Internacional El Edén',
    city: 'Armenia',
    gates: 'B3',
    country: 'colombia',
  },
  {
    iata: 'BAQ',
    name: 'Aeropuerto Internacional Ernesto Cortissoz',
    city: 'Barranquilla',
    gates: 'B2',
    country: 'colombia',
  },
  {
    iata: 'BOG',
    name: 'Aeropuerto Internacional El Dorado ',
    city: 'Bogotá',
    gates: 'B3',
    country: 'colombia',
  },
  {
    iata: 'BGA',
    name: 'Aeropuerto Internacional Palonegro',
    city: 'Bucaramanga',
    gates: 'E1',
    country: 'colombia',
  },
  {
    iata: 'CLO',
    name: 'Aeropuerto Internacional Alfonso Bonilla Aragón ',
    city: 'Cali',
    gates: 'D9',
    country: 'colombia',
  },
  {
    iata: 'CUC',
    name: 'Aeropuerto Internacional Camilo Daza',
    city: 'Cúcuta',
    gates: 'C3',
    country: 'colombia',
  },
  {
    iata: 'CTG',
    name: 'Aeropuerto Internacional Rafael Núñez',
    city: 'Cartagena',
    gates: 'C2',
    country: 'colombia',
  },
  {
    iata: 'LET',
    name: 'Aeropuerto Internacional Alfredo Vásquez Cobo',
    city: 'Leticia',
    gates: 'A3',
    country: 'colombia',
  },
  {
    iata: 'MDE',
    name: 'Aeropuerto Internacional José María Córdova',
    city: 'Medellín',
    gates: 'A5',
    country: 'colombia',
  },
  {
    iata: 'PEI',
    name: 'Aeropuerto Internacional Matecaña',
    city: 'Pereira',
    gates: 'A9',
    country: 'colombia',
  },
  {
    iata: 'ADZ',
    name: 'Aeropuerto Internacional Gustavo Rojas Pinilla ',
    city: 'San Andrés',
    gates: 'E2',
    country: 'colombia',
  },
  {
    iata: 'SMR',
    name: 'Aeropuerto Internacional Simón Bolívar ',
    city: 'Santa Marta',
    gates: 'D1',
    country: 'colombia',
  },
  {
    iata: 'MTR',
    name: 'Aeropuerto Internacional Los Garzones',
    city: 'Montería',
    gates: 'E2',
    country: 'colombia',
  },
  {
    iata: 'RCH',
    name: 'Aeropuerto Internacional Almirante Padilla',
    city: 'Riohacha',
    gates: 'C4',
    country: 'colombia',
  },
  {
    iata: 'LMN',
    name: 'Aeropuerto Jorge Isaacs',
    city: 'Maicao',
    gates: 'A4',
    country: 'colombia',
  },
];
