export let flightsArr = [
    {
        id: 1,
        cityImg: 'https://www.latamairlines.com/content/dam/latamxp/sites/destinos/colombia/deals/CLO-deals.jpg.transform/md/image.jpg',
        city: 'Cali',
        // departDate: { day: 18, month: 09, year: 2022 },
        departDate: "18/11/22",
        returnDate: '',
        tripClass: 'Economy',
        price: 192950.00,
        taxes: 'Tasas incluidas',
        tripType: 'Vuelo directo',
    },
    {
        id: 2,
        cityImg: 'https://www.latamairlines.com/content/dam/latamxp/sites/destinos/colombia/deals/ADZ-deals.jpg.transform/md/image.jpg',
        city: 'Isla San Andrés',
        // departDate: { day: 18, month: 09, year: 2022 },
        departDate: '18/11/22',
        returnDate: '',
        tripClass: 'Economy',
        price: 278800.00,
        taxes: 'Tasas incluidas',
        tripType: 'Vuelo directo',
    },
    {
        id: 3,
        cityImg: 'https://www.latamairlines.com/content/dam/latamxp/sites/destinos/estados-unidos/deals/MIA-deals.jpg.transform/md/image.jpg',
        city: 'Miami',
        // departDate: { day: 18, month: 09, year: 2022 },
        departDate: '26/11/22',
        returnDate: '06/12/22',
        tripClass: 'Economy',
        price: 1766510.00,
        taxes: 'Tasas incluidas',
        tripType: 'Vuelo directo',
    },
    {
        id: 4,
        cityImg: 'https://www.latamairlines.com/content/dam/latamxp/sites/destinos/colombia/deals/MDE2-deals.jpg.transform/md/image.jpg',
        city: 'Medellín',
        // departDate: { day: 18, month: 09, year: 2022 },
        departDate: '20/11/22',
        returnDate: '',
        tripClass: 'Economy',
        price: 203240.00,
        taxes: 'Tasas incluidas',
        tripType: 'Vuelo directo',
    },
    {
        id: 5,
        cityImg: 'https://www.latamairlines.com/content/dam/latamxp/sites/destinos/colombia/deals/CTG2-deals.jpg.transform/md/image.jpg',
        city: 'Cartagena de indias',
        // departDate: { day: 18, month: 09, year: 2022 },
        departDate: '18/11/22',
        returnDate: '',
        tripClass: 'Economy',
        price: 284311.00,
        taxes: 'Tasas incluidas',
        tripType: 'Vuelo directo',
    },
    {
        id: 6,
        cityImg: 'https://www.latamairlines.com/content/dam/latamxp/sites/destinos/colombia/deals/smr-deals.jpg.transform/md/image.jpg',
        city: 'Santa Marta',
        // departDate: { day: 18, month: 09, year: 2022 },
        departDate: '18/11/22',
        returnDate: '',
        tripClass: 'Economy',
        price: 224240.00,
        taxes: 'Tasas incluidas',
        tripType: 'Vuelo directo',
    },
]